name: Beispiellösung CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: prepare solution
      run: cp -r beispiel_lösung/* ./
    - uses: egor-tensin/setup-gcc@v1
      name: install 32bit gcc
      with:
        platform: x32
    - name: Set up NASM
      uses: ilammy/setup-nasm@v1.2.0
    - name: make
      run: make -j
    - name: test
      run: ./test
